controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\DadataApi;
use app\models\KeyMail;
use app\models\Product;
use app\models\ProductSearch;
use app\models\User;
use app\models\UserForm;
use Yii;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $products=Product::find()->orderBy('id')->offset('1')->limit('4')->all();
        $categories = Category::find()->all();
        return $this->render('index',[
            'products'=>$products,
            'categories'=>$categories
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
          /*  if (Yii::$app->user->identity->user_type==='2')
                return $this->render('/cooker');
            if (Yii::$app->user->identity->user_type==='3')
                return $this->render('/admin');*/
            return $this->goHome();
        }

        $model = new UserForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {

            if ($model->getType()==2)
            {
                return $this->redirect('/cooker');
            }
            return $this->goBack();
        }
        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }
    public function actionCode()
    {
        return $this->render('code');
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionRegistration()
    {

        $scenario = \Yii::$app->request->post('type', 'user');

        $model=new User(['scenario' => $scenario]);

        if (!\Yii::$app->request->isPost)
        {
            return  $this->render('registration', [
                    'model'=>$model
            ]);
        }
        if($model->load(\Yii::$app->request->post())){
            //print_r(\Yii::$app->request->post());
            if($model->validate()) {
                $users = User::find()->where(['email' => $model->email])->all(); // если этой проверки нет , то при повторной
                // отправке формы
                // user записывается опять

                if(count($users) > 0) {
                    return $this->render('index', [

                    ]);
                }
                /*print_r($model);
                exit();*/
                if($model->save()) {

                    $model->defaultImage();
                    $model->sendCode();

                    return $this->render('code', [

                    ]);
                }

            } else {
                return  $this->render('registration', [
                    'model'=>$model
                ]);
            }
        }

    }



    public function actionCheckKey()
    {

        //if(Yii::$app->request->post('val')){
            $check=Yii::$app->request->post('code');
            $userKey = KeyMail::findOne(['value_key' => $check=Yii::$app->request->post('code')]);
            if(is_object($userKey)) {
                $user = User::findOne(['id' => $userKey->user_id]);
                $user->scenario = User::SCENARIO_USER;
                if(is_object($user)) {
                    $userKey->used = 1;
                    $user->active = 1;
                    if(!$user->save()){
                        print_r($user->getErrors()); exit();
                    }
                    $userKey->save();
                    return $this->redirect('login');

                }
            }else {
                $error='Неверный код';
                return $this->render('code', [
                    'error'=>$error

                ]);
            }

    }

    public function actionAgree()
    {
        return $this->render('agree');
    }

    public function actionTest()
    {
        $okveds=['10.71','52.61',' 55.52',' 47.81', '47.91', '47.99'];
        $api = new DadataApi();
        $result=$api->checkInn('9102171153');
        print_r($result);

        $suggestions= $result['suggestions'];
        $s0=$suggestions['0'];
        $data=$s0['data'];

        $management=$data['management'];
        $state=$data['state'];
        $address=$data['address'];
        $dataInAddress=$address['data'];

        //print_r($state);
       /* echo $dataInAddress['region_kladr_id'];*/


    /*    if($dataInAddress['region_kladr_id']==9200000000000 || $dataInAddress['region_kladr_id']==9100000000000){
            echo 'РЕГИОН';
        }*/

       /* if($management['name']=='Володина Надежда Яковлевна'){
            echo $management['name'];
        }*/
        var_dump( $management);

      /*  if($state['status']=='ACTIVE'){
            echo $state['status'];
        }

        if(in_array($data['okved'], $okveds)){
            echo 'ОКВЭД';
        }*/


    }

}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

/*$this->title = 'О нас';
$this->params['breadcrumbs'][] = $this->title;*/
?>
<div class="content-wrapper" style="text-align: center">
    <div class="container">
        <div class="row content">
            <div class="col-xs-12">
                <h1>Где купить и где дешевле</h1>
                <h4>
                    Устали искать кондитерские изделия на праздник? Переживаете за качество? Волнуетесь заказать у дилетанта?
                </h4>
                <br>
                <div class="row">
                    <div class="col-sm-4">
                        <img src="/images/about1.jpg" width="300px">
                    </div>
                    <div class="col-sm-4">
                        <img src="/images/about2.jpg" width="300px">
                    </div>
                    <div class="col-sm-4">
                        <img src="/images/about3.jpg" width="300px">
                    </div>
                </div>
                <br>
                <h4>
                    Внимание! Мы создали эту классную площадку специально для Вас.&nbsp;
                </h4>
              <!--  <h2>CAKES HOME</h2>-->
                <h3>
                    Теперь товары со всех кондитерских, описание и цены - все в одном месте!&nbsp;Здесь вы не покупаете, но ищете лучшие условия, необходимые товары, удобный способ доставки.&nbsp; </h3>
                <p>
                    <br>
                </p>
                <p>
                    1. Введите в поиск нужный вам торт, десерт или выпечку. Или же воспользуйтесь фильтрами
                </p>
                <p>
                    2. Выберете понравившийся товар
                </p>
                <p>
                    3. Почитайте про сам товар, посмотрите фотографии
                </p>
                <p>
                    4. Узнайте информацию о кондитере, способах связи и условиях доставки
                </p>
                <p>
                    4. Готовы купить? Связывайтесь с кондитером на ссылки и покупайте напрямую у кондитера.
                </p>
                <p>
                    <br>
                </p>
                <h3>
                    НЕ НАШЛИ, ЧТО ИСКАЛИ? НЕ БЕДА!
                </h3>
                <p>
                    <br>
                </p>
                <p>
                    1. Добавьте заявку и укажите все пожелания к десерту, цене, способе доставки и сроки выполнения
                </p>
                <p>
                    2. Кондитеры увидят Ваше объявления и свяжутся к Вами!
                </p>
                <p>
                    <br>
                </p>
                <h2>
                    ЧЕМ МЫ ВАМ ПОЛЕЗНЫ
                </h2>

                <p>
                    ВЫ ПОКУПАЕТЕ ТОВАРЫ НЕ У НАС, А НАПРЯМУЮ В ВЫБРАННЫХ МАГАЗИНАХ
                </p>
                <h2><br>
                </h2>
                <h2>Найдите нужные кондитерские товары прямо сейчас! Сравните цены и купите&nbsp;дешевле.</h2>
            </div>
        </div>
    </div>
</div>

На специализированном сервисе мы размещаем товары частных кондитеров, а также фирм, которые занимаются изготовлением под заказ различных сладостей: тортов, капкейков, пирожных, макарунс, пряников и т.д. Цель проекта – в одном месте объединить кондитеров, создать для них дополнительный канал продаж и предоставить пользователям максимальный выбор сладостей на любой праздник.

views/site/agree.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

/*$this->title = 'О нас';
$this->params['breadcrumbs'][] = $this->title;*/
?>
<h1 class="inner">Пользовательское соглашение для сайта Cakes Home</h1>
<p style="margin-bottom: 0.0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal"><span>Настоящее Соглашение определяет условия использования Пользователями материалов и сервисов сайта </span><a href="http://cakeshome.ru"><span>www</span><span>.cakeshome.ru</span></a><span>&nbsp;&nbsp; (далее&nbsp;— «Сайт»).</span></p>
<p><strong>1.Общие условия</strong></p>
<p>1.1. Использование материалов и сервисов Сайта регулируется нормами действующего законодательства Российской Федерации.</p>
<p>1.2. Настоящее Соглашение является публичной офертой. Получая доступ к материалам Сайта Пользователь считается присоединившимся к настоящему Соглашению. </p>
<p>1.3. Администрация Сайта вправе в любое время в одностороннем порядке изменять условия настоящего Соглашения. Такие изменения вступают в силу по истечении 3 (Трех) дней с момента размещения новой версии Соглашения на сайте. При несогласии Пользователя с внесенными изменениями он обязан отказаться от доступа к Сайту, прекратить использование материалов и сервисов Сайта.</p>
<p><strong>2. Обязательства Пользователя</strong></p>
<p>2.1. Пользователь соглашается не предпринимать действий, которые могут рассматриваться как нарушающие российское законодательство или нормы международного права, в том числе в сфере <a href="http://copyright.ru/intellectual/" title="интеллектуальной собственности">интеллектуальной собственности</a>, <u><a href="http://copyright.ru/ru/documents/avtorskoe_pravo/avtorskie_prava/" title="авторских">авторских</a> </u>и/или <u><a href="http://copyright.ru/ru/documents/avtorskoe_pravo/smegnie_prava/" title="смежных правах">смежных правах</a></u>, а также любых действий, которые приводят или могут привести к нарушению нормальной работы Сайта и сервисов Сайта.</p>
<p>2.2. Использование материалов Сайта без согласия <a href="http://copyright.ru/documents/avtorskoe_pravo/pravoobladateli/" title="правообладателей">правообладателей</a> не допускается (статья 1270&nbsp;Г.К РФ). Для правомерного использования материалов Сайта необходимо заключение <u><a href="http://copyright.ru/ru/documents/avtorskoe_pravo/peredacha_avtorskih_prav/" title="лицензионных договоров">лицензионных договоров</a></u> (получение лицензий) от Правообладателей. </p>
<p>2.3. При <a href="http://copyright.ru/library/zakonodatelstvo/gk_rf_obschee_zakonodatel/grazhdanskii_kodeks_RF_4_chast/glava_70__avtorskoe_pravo/#20" title="цитировании">цитировании</a> материалов Сайта, включая охраняемые авторские произведения, ссылка на Сайт обязательна (подпункт 1 пункта 1 статьи 1274&nbsp;Г.К РФ).</p>
<p>2.4. Комментарии и иные записи Пользователя на Сайте не должны вступать в противоречие с требованиями законодательства Российской Федерации и общепринятых норм морали и нравственности.</p>
<p>2.5. Пользователь предупрежден о том, что Администрация Сайта не несет ответственности за посещение и использование им внешних ресурсов, ссылки на которые могут содержаться на сайте. </p>
<p>2.6. Пользователь согласен с тем, что Администрация Сайта не несет ответственности и не имеет прямых или косвенных обязательств перед Пользователем в связи с любыми возможными или возникшими потерями или убытками, связанными с любым содержанием Сайта, <u><a href="http://copyright.ru/ru/documents/registraciy_avtorskih_prav/" title="регистрацией авторских прав">регистрацией авторских прав</a></u> и сведениями о такой регистрации, товарами или услугами, доступными на или полученными через внешние сайты или ресурсы либо иные контакты Пользователя, в которые он вступил, используя размещенную на Сайте информацию или ссылки на внешние ресурсы.</p>
<p>2.7. Пользователь принимает положение о том, что все материалы и сервисы Сайта или любая их часть могут сопровождаться рекламой. Пользователь согласен с тем, что Администрация Сайта не несет какой-либо ответственности и не имеет каких-либо обязательств в связи с такой рекламой.</p> <p><strong>3. Прочие условия</strong></p>
<p>3.1. Все возможные споры, вытекающие из настоящего Соглашения или связанные с ним, подлежат разрешению в соответствии с действующим законодательством Российской Федерации. </p>
<p>3.2. Ничто в Соглашении не может пониматься как установление между Пользователем и Администрации Сайта агентских отношений, отношений товарищества, отношений по совместной деятельности, отношений личного найма, либо каких-то иных отношений, прямо не предусмотренных Соглашением.</p>
<p>3.3. Признание судом какого-либо положения Соглашения недействительным или не подлежащим принудительному исполнению не влечет недействительности иных положений Соглашения.</p>
<p>3.4. Бездействие со стороны Администрации Сайта в случае нарушения кем-либо из Пользователей положений Соглашения не лишает Администрацию Сайта права предпринять позднее соответствующие действия в защиту своих интересов и <a href="http://copyright.ru/documents/zashita_avtorskih_prav/" title="защиту авторских прав">защиту авторских прав</a> на охраняемые в соответствии с законодательством материалы Сайта.</p>
<p><strong>Пользователь подтверждает, что ознакомлен со всеми пунктами настоящего Соглашения и безусловно принимает их.</strong></p>

views/site/code.php
<?php



use yii\helpers\Html;

/*$this->title = 'Подтверждение';
$this->params['breadcrumbs'][] = $this->title;*/
?>

<link  rel="stylesheet" href="/css/login.css">
<div class="row">
    <div class="col-md-3  mx-auto p-0"></div>
    <div class="col-md-6 mx-auto p-0">
        <div class="card">
            <div class="login-box">
                <div class="login-snip"> <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Вход</label>
                    <div class="login-space">
                        <div class="login">
                            <?php if (isset($error)):?>
                            <div class="help-block-error"> <?=$error?></div>
                            <?php endif;?>
                                <form action="/site/check-key" method="post">
                                <input type="hidden" name="<?= \Yii:: $app->getRequest()->csrfParam ?>" value="<?= \Yii:: $app->getRequest()->getCsrfToken() ?>">
                                <div class="group"> <label class="label">Код </label> <input id="user" type="text" class="input" autocomplete="off" placeholder="Введите код" name="code" aria-required="true"> </div>
                                <div class="form-group">
                                    <div class="group"> <input type="submit" class="button" value="Подтвердить"> </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

/*$this->title = $name;*/
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <div class="col-sm-12" style="background: rgba(78,76,76,0.44) ; text-align: center">
        <h1> <img src="/images/error.png" width="100px" height="100px"> Упс! Такой страницы не существует:(</h1>
        <h4 style="text-align: center">
            Пожалуйста, свяжитесь с нами, если считаете, что это ошибка сервера. Спасибо.
        </h4>
    </div>


</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Cakes Home';

use yii\helpers\Html; ?>

<link rel="stylesheet" href="/css/forIndex.css">

<div class="thumbnail"><img class="thumbnail__img" src="/images/categories/5.jpg" />
    <div class="thumbnail__content">
        <div class="thumbnail__title">CAKES HOME</div>
        <div class="thumbnail__subtitle">

                <form method="get" action="/catalog/search">
                    <input placeholder="Эклер, день рождения" name="search_text" autocomplete="off">
                    <button class="btn" title="Найти" aria-label="Search">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </button>
                </form>

        </div>
        <div class="thumbnail__link"></div>
    </div>
</div>
<div class="categories" >
    <?php foreach ($categories as $category):?>
        <div class="categorybox categorybox<?=$category->id?>">
            <div class="categoryName">
                <h3> <?= Html::a("$category->name", ['/catalog/category', 'id' => $category->id]) ?></h3>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<div class="cooker col-md-12 col-sm-12">
    <div class="image col-md-5 col-sm-12">
    <img src="/images/mlogo.png" alt="cooker" width="450">
    </div>
    <div class="text col-md-7 col-sm-12">
        <h1>Кондитер?</h1>
        <h3> <?= Html::a('Зарегистрируйся', ['/site/registration'], ['class' => '']) ?> за пару минут и получите доступ к личному кабинету. Размещайте свои десерты в каталоге, добавляте фотографии и получайте поток новых клиентов!  </h3>
    </div>
</div>

<script>
    $(document).ready(function () {
        $(window).scroll(function(){
            if($(window).width()>500) {
                if ($(window).scrollTop() > 120) {
                    $('.cooker').show('slow');
                } else $('.cooker').hide('fast');
            }

            if ($(window).scrollTop() > 110) {
                $('.navbar-fixed-top').css(' background', 'red');

            }

        });


    });

</script>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/*$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;*/
?>
<link  rel="stylesheet" href="/css/login.css">

<div class="col-md-6 col-md-offset-3 col-xs-12">
    <div class="card">
        <div class="login-box">
            <div class="login-snip"> <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Вход</label>
                <!--<input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Регистрация</label>-->
                <div class="login-space">
                    <div class="login">

                        <?php $form = ActiveForm::begin([
                            'fieldConfig' => [
                                'template' => "<div class='group'><label class='label'>{label}</label>{input}{error}</div>",
                                'labelOptions' => ['class' => 'label'],
                            ],
                        ]); ?>

                        <?= $form->field($model, 'email')->textInput(['class' => 'input', 'placeholder'=>'Введите E-mail']) ?>

                        <?= $form->field($model, 'password')->passwordInput(['class'=>'input', 'placeholder'=>'Введите пароль'])->label('Пароль') ?>


                        <?= $form->field($model, 'rememberMe')->checkbox([
                            'template' =>  "<div class='group'>{input}<label for='check'><span class='icon'></span>{label}</label></div>",
                            'id'=>"check", 'class'=>"check"
                        ])
                            ->label('Запомнить меня')?>

                        <div class="group"> <input type="submit" class="button" value="Войти"> </div>
                        <?php ActiveForm::end(); ?>
                        <div class="hr"></div>
<!--                        <div class="foot"> <a href="#">Забыли пароль?</a> </div>-->
                        <div class="foot"> <a href="/site/registration" >Зарегистрироваться?</a> </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/registration.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form ActiveForm */
/*$this->title = 'Registration';
$this->params['breadcrumbs'][] = $this->title;*/
?>

<link  rel="stylesheet" href="/css/registration.css">
<div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-12 ">
        <div class="card">
            <div class="sign-up-box">
                <div class="sign-up-ship">
                    <input id="tab-1" type="radio" name="tab" class="sign-up-user" <?=$model->scenario=='cookers'? '':'checked'?>><label for="tab-1" class="tab">Регистрация</label>
                    <input id="tab-2" type="radio" name="tab" class="sign-up-cooker" <?=$model->scenario=='cookers'? 'checked':''?>><label for="tab-2" class="tab">Для кондитера</label>
                    <div class="sign-up-space">
                        <div class="sign-up">
                            <?php ($model->scenario = \app\models\User::SCENARIO_USER) ?>
                            <?php $form = ActiveForm::begin([
                                'fieldConfig' => [
                                    'template' => "<div class='group'><label class='label'>{label}</label>{input}{error}</div>",
                                    'labelOptions' => ['class' => 'label'],
                                ],
                            ]); ?>

                            <?= $form->field($model, 'email')->textInput(['class' => 'input', 'placeholder'=>'Введите E-mail','autocomplete'=>"off"]) ?>

                            <?= $form->field($model, 'password')->passwordInput(['class'=>'input', 'placeholder'=>'Введите пароль'])->label('Пароль') ?>
                            <input type="hidden" name="type" value="user">
                            <div class='group'><input type="hidden" name="userAgree" value="0"><input type="checkbox" class="check" name="userAgree" value="1" checked><label for='check'><span class='icon'></span><label for="check">  <a href="/site/agree">&nbsp;Согласие на обработку персональных данных</a></label></label></div>

                            <div class="group"> <input type="submit" class="button" value="Зарегистрироваться"> </div>
                            <?php ActiveForm::end(); ?>
                            <div class="hr"></div>
                        </div>
                        <div class="sign-up-cooker-form">
                            <?php ($model->scenario = \app\models\User::SCENARIO_COOKER) ?>
                            <?php $form = ActiveForm::begin([
                                'fieldConfig' => [
                                    'template' => "<div class='group'><label class='label'>{label}</label>{input}{error}</div>",
                                    'labelOptions' => ['class' => 'label'],
                                ],
                            ]); ?>



                            <?= $form->field($model, 'first_name')->textInput(['class' => 'input', 'placeholder'=>'Введите имя','autocomplete'=>"off"]) ?>

                            <?= $form->field($model, 'second_name')->textInput(['class' => 'input', 'placeholder'=>'Введите фамилию','autocomplete'=>"off"]) ?>

                            <?= $form->field($model, 'third_name')->textInput(['class' => 'input', 'placeholder'=>'Введите отчество','autocomplete'=>"off"]) ?>

                            <?= $form->field($model, 'inn_number')->textInput(['class' => 'input', 'placeholder'=>'Введите ИНН','autocomplete'=>"off"]) ?>

                            <?= $form->field($model, 'phone')->textInput(['class' => 'input', 'placeholder'=>'Введите телефон','autocomplete'=>"off"]) ?>

                            <?= $form->field($model, 'sity')->textInput(['class' => 'input', 'placeholder'=>'Введите город']) ?>

                            <?= $form->field($model, 'email')->textInput(['class' => 'input', 'placeholder'=>'Введите E-mail','autocomplete'=>"off"]) ?>

                            <?= $form->field($model, 'password')->passwordInput(['class'=>'input', 'placeholder'=>'Введите пароль'])->label('Пароль') ?>

                            <input type="hidden" name="type" value="cookers">
                            <div class='group'><input type="hidden" name="userAgree" value="0"><input type="checkbox" class="check" name="userAgree" value="1" checked><label for='check'><span class='icon'></span><label for="check"> <a href="/site/agree">&nbsp;Согласие на обработку персональных данных</a></label></label></div>
                            <div class="group"> <input type="submit" class="button" value="Зарегистрироваться"> </div>
                            <?php ActiveForm::end(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-2  mx-auto p-0" id="information">

    </div>
</div>

<script>
    $(document).ready(function () {

        $('#information').hide();

        $('.sign-up-ship>.sign-up-cooker').on('click', function () {
            $('#information').show();
        });

        $('.sign-up-ship>.sign-up-user').on('click', function () {
            $('#information').hide();
        });

    });


</script>